import path from 'node:path';
import type {
  ParsedProject,
  RouteMethodInfo,
  OpenApiDocument,
} from '../types/index.js';

export class CodeGenerator {
  constructor(private parsed: ParsedProject) {}

  public generateHonoRoutes(outputFilePath: string): string {
    const outDir = path.dirname(path.resolve(outputFilePath));
    const importStatements: string[] = [
      `import type { Hono } from 'hono';`,
    ];

    const controllerInstances: string[] = [];
    const routeRegistrations: string[] = [];

    for (const controller of this.parsed.controllers) {
      let relImport = path.relative(outDir, controller.filePath);
      relImport = relImport.replace(/\\/g, '/');
      if (!relImport.startsWith('.')) relImport = `./${relImport}`;
      // Strip .ts extension for ESM import
      relImport = relImport.replace(/\.ts$/, '.js');

      importStatements.push(
        `import { ${controller.className} } from '${relImport}';`
      );

      const varName = `${this.uncapitalize(controller.className)}`;
      controllerInstances.push(`  const ${varName} = new ${controller.className}();`);

      for (const method of controller.methods) {
        const fullPath = this.combinePaths(controller.basePath, method.path);
        const honoPath = fullPath;
        const handlerCode = this.generateHandlerCode(varName, method);

        routeRegistrations.push(
          `  app.${method.httpMethod}('${honoPath}', ${handlerCode});`
        );
      }
    }

    return `// Auto-generated by @developersailor/gea-openapi-decorators. DO NOT EDIT.
// Zero-reflection, Ahead-of-Time static Hono routes for GeaStack C++ compilation.

${importStatements.join('\n')}

export function registerRoutes(app: Hono): void {
${controllerInstances.join('\n')}

${routeRegistrations.join('\n')}
}
`;
  }

  private generateHandlerCode(controllerVar: string, method: RouteMethodInfo): string {
    const paramExtracts: string[] = [];
    const callArgs: string[] = [];

    // Sort params by index
    const sortedParams = [...method.params].sort((a, b) => a.index - b.index);

    for (const p of sortedParams) {
      if (p.source === 'param') {
        const varName = `param_${p.name || p.paramName}`;
        paramExtracts.push(`    const ${varName} = c.req.param('${p.name || p.paramName}');`);
        callArgs.push(p.type === 'number' ? `Number(${varName})` : varName);
      } else if (p.source === 'query') {
        const varName = `query_${p.name || p.paramName}`;
        paramExtracts.push(`    const ${varName} = c.req.query('${p.name || p.paramName}');`);
        callArgs.push(p.type === 'number' ? `Number(${varName})` : varName);
      } else if (p.source === 'body') {
        const varName = `body_${p.paramName}`;
        paramExtracts.push(`    const ${varName} = await c.req.json();`);
        callArgs.push(varName);
      } else if (p.source === 'header') {
        const varName = `header_${(p.name || p.paramName).replace(/[^a-zA-Z0-9]/g, '_')}`;
        paramExtracts.push(`    const ${varName} = c.req.header('${p.name || p.paramName}');`);
        callArgs.push(varName);
      } else if (p.source === 'context') {
        callArgs.push('c');
      }
    }

    const awaitKeyword = method.isAsync ? 'await ' : '';
    const statusCode = method.statusCode ?? (method.httpMethod === 'post' ? 201 : 200);

    const callExpression = `${awaitKeyword}${controllerVar}.${method.methodName}(${callArgs.join(', ')})`;

    const lines: string[] = [
      `async (c: any) => {`,
      ...paramExtracts,
      `    const result = ${callExpression};`,
      `    if ((result as any) instanceof (Response as any)) {`,
      `      return result;`,
      `    }`,
      `    if (result === undefined || result === null) {`,
      `      return c.body(null as any, ${statusCode === 200 ? 204 : statusCode});`,
      `    }`,
      `    return c.json(result, ${statusCode});`,
      `  }`,
    ];

    return lines.join('\n');
  }

  public generateOpenApiSpec(title: string = 'GeaStack API', version: string = '1.0.0'): OpenApiDocument {
    const doc: OpenApiDocument = {
      openapi: '3.1.0',
      info: {
        title,
        version,
        description: 'Generated by @developersailor/gea-openapi-decorators',
      },
      paths: {},
      components: {
        schemas: {},
      },
    };

    // Add models
    for (const model of this.parsed.models) {
      const properties: Record<string, any> = {};
      const requiredProps: string[] = [];

      for (const prop of model.properties) {
        properties[prop.name] = {
          type: this.mapTsTypeToOpenApi(prop.type),
          description: prop.description,
          example: prop.example,
        };
        if (prop.required) {
          requiredProps.push(prop.name);
        }
      }

      doc.components!.schemas![model.className] = {
        type: 'object',
        properties,
        required: requiredProps.length > 0 ? requiredProps : undefined,
      };
    }

    // Add paths
    for (const controller of this.parsed.controllers) {
      for (const method of controller.methods) {
        const fullPath = this.combinePaths(controller.basePath, method.path);
        const openApiPath = fullPath.replace(/:([a-zA-Z0-9_]+)/g, '{$1}');

        if (!doc.paths[openApiPath]) {
          doc.paths[openApiPath] = {};
        }

        const tags = Array.from(new Set([...controller.tags, ...(method.tags || [])]));
        const parameters: any[] = [];
        let requestBody: any = undefined;

        for (const p of method.params) {
          if (p.source === 'param') {
            parameters.push({
              name: p.name || p.paramName,
              in: 'path',
              required: true,
              schema: { type: this.mapTsTypeToOpenApi(p.type) },
            });
          } else if (p.source === 'query') {
            parameters.push({
              name: p.name || p.paramName,
              in: 'query',
              required: p.required,
              schema: { type: this.mapTsTypeToOpenApi(p.type) },
            });
          } else if (p.source === 'header') {
            parameters.push({
              name: p.name || p.paramName,
              in: 'header',
              required: p.required,
              schema: { type: 'string' },
            });
          } else if (p.source === 'body') {
            requestBody = {
              required: true,
              content: {
                'application/json': {
                  schema: this.isCustomModel(p.type)
                    ? { $ref: `#/components/schemas/${p.type}` }
                    : { type: this.mapTsTypeToOpenApi(p.type) },
                },
              },
            };
          }
        }

        const statusCode = method.statusCode ?? (method.httpMethod === 'post' ? 201 : 200);

        doc.paths[openApiPath][method.httpMethod] = {
          summary: method.summary || `${method.methodName} operation`,
          description: method.description,
          tags: tags.length > 0 ? tags : undefined,
          deprecated: method.deprecated,
          parameters: parameters.length > 0 ? parameters : undefined,
          requestBody,
          responses: {
            [statusCode]: {
              description: statusCode === 201 ? 'Created' : 'Successful response',
              content: {
                'application/json': {
                  schema: { type: 'object' },
                },
              },
            },
          },
        };
      }
    }

    return doc;
  }

  private mapTsTypeToOpenApi(type: string): string {
    switch (type.toLowerCase()) {
      case 'number':
        return 'integer';
      case 'boolean':
        return 'boolean';
      case 'string':
        return 'string';
      case 'any':
      default:
        return 'string';
    }
  }

  private isCustomModel(type: string): boolean {
    return this.parsed.models.some((m) => m.className === type);
  }

  private combinePaths(base: string, sub: string): string {
    const cleanBase = base.endsWith('/') ? base.slice(0, -1) : base;
    const cleanSub = sub.startsWith('/') ? sub : `/${sub}`;
    let result = `${cleanBase}${cleanSub}`;
    if (result.length > 1 && result.endsWith('/')) {
      result = result.slice(0, -1);
    }
    return result === '' ? '/' : result;
  }

  private uncapitalize(str: string): string {
    return str.charAt(0).toLowerCase() + str.slice(1);
  }
}
